#!/usr/bin/env bash
# a bash script that displays information about subdomains

sub_info() {
	cmd=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	
	echo "$2 $cmd" | awk '{print "The subdomain " $1 " is a " $2" record and points to " $3}'
}

if [[ "$#" -eq 1 ]]; then # if args is 1
	sub_info "$1" "www"
	sub_info "$1" "lb-01"
	sub_info "$1" "web-01"
	sub_info "$1" "web-02"
elif [[ "$#" -eq 2 ]]; then  # if args is 2
	sub_info "$1" "$2"
fi
