#!/usr/bin/env bash
# a bash script that transfers a file from our client to a server

transfer_file () {
	if [[ $# -lt 4 ]]; then
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		exit 1
	fi

	file_path="$1"
	ip_v4="$2"
	user_name="$3"
	ssh_token="$4"

	# disable strict host key checking for scp
	export SCP_OPTIONS="-o StrictHostKeyChecking=no"

	scp $SCP_OPTIONS -i "$ssh_token" "$file_path" "$user_name"@"$ip_v4":~/
}
transfer_file "$@" # to pass all script arguments to the function
