#!/usr/bin/env bash
# a script that installs nginx and configures a custom 404 page that
# contains a string using sed

sudo apt -y update
sudo apt -y install nginx
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo rm /etc/nginx/sites-enabled/default
sudo rm /etc/nginx/sites-enabled/some_page
sudo tee /etc/nginx/sites-available/some_page <<EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        location / {
                root /var/www/html;
                index some_page.html;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}
EOF

sudo sed -i 's/error_page 404 \/404.html;/error_page 404 \/404.html;\n        error_page 404 \/404_custom.html;/g' /etc/nginx/sites-available/some_page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_custom.html

sudo ln -s /etc/nginx/sites-available/some_page /etc/nginx/sites-enabled/

sudo service nginx restart
